language: cpp
sudo: false
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
dist: bionic
osx_image: xcode11

install:
  - cmake -DCMAKE_INSTALL_PREFIX=`pwd`/inst .
  - make
  - make install
script:
  - ./tests.sh
notifications:
  email: false
