language: cpp
sudo: false
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
dist: bionic
osx_image: xcode11

install:
  - make
script:
  - ./colors
# this succeeds:
  - ./colors < README.md
# but this fails:
  - ! (./keys < README.md)
notifications:
  email: false
