name: Windows CI

on: [push, pull_request]

jobs:
  Build:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test
      run: |
          ci\compile_test.bat
          examples\Release\colors.exe
